### PR TITLE
Replace Travis with GitHub workflows

### PR DESCRIPTION
**Pull request by markedwards**
Replaces the broken Travis setup with GitHub workflows, and updates the badges in README.md.

Also includes a refactor in aiodataloader.py to resolve flake8 errors.

### CODE REVIEW

**Comment by markedwards** [comment]
@syrusakbary or @Cito, any comments on this?  Probably further additions or improvements can be made, but I want to get the pipelines running in an equivalent manner first.

**Comment by Cito** [comment]
@markedwards Looks good to me.

**Comment by markedwards** [comment]
> @markedwards Looks good to me.

Thanks for taking a look @Cito.  Could also use your attention on #25 if you have bandwidth.  That's the next goal, to make aiodataloader fully typed, and that probably means dropping support for python 3.5.

The diff is still a work-in-progress, so still a bunch left to do there.  But prior to actually merging and doing a subsequent release, would love more eyes.

**Comment by Cito** [comment]
PR #25 also looks good to me, but currently don't have the bandwidth to test or check in detail. And yes, you should definitely drop Python 3.5. It is not supported by GraphQL-Core 3 and in the upcoming 3.3 release of GraphQL-core I'll even drop Python 3.6 (EOL was Dec 2021). Also check compatibility/necessity of `typing_extensions` with various Python versions.

**Pull request merged**
